# Generated by Django 5.0.6 on 2024-06-09 21:26

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaborateur", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commercial",
            fields=[
                (
                    "collaborateur_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Commercial",
                "verbose_name_plural": "Commerciaux",
            },
            bases=("collaborateur.collaborateur",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Gestion",
            fields=[
                (
                    "collaborateur_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gestion",
                "verbose_name_plural": "Gestions",
            },
            bases=("collaborateur.collaborateur",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Support",
            fields=[
                (
                    "collaborateur_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Support",
                "verbose_name_plural": "Supports",
            },
            bases=("collaborateur.collaborateur",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="collaborateur",
            name="role",
        ),
        migrations.AlterField(
            model_name="collaborateur",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
