# Generated by Django 5.0.6 on 2024-06-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaborateur", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaborateur",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
