# Generated by Django 5.0.6 on 2024-06-20 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaborateur", "0002_alter_collaborateur_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaborateur",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaborateurs",
                to="collaborateur.role",
            ),
        ),
    ]
